language: node_js
env:
  - CXX=g++-4.8 DATA_DIR=./test/data
node_js:
  - '6'
  - '5'
  - '4'
before_install:
  - sudo apt-get update
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8